-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(20) NOT NULL,
    JOB VARCHAR2(20),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(10),
    COMM NUMBER(7),
    DEPTNO NUMBER(2)
);

-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(15) NOT NULL
);
